kind: pipeline
name: default

steps:
- name: publish-frpc
  image: plugins/docker
  settings:
    repo: v7lin/frpc
    context: frpc
    dockerfile: Dockerfile
    target: prod
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
    - 0.22.0
    - latest

- name: publish-frps
  image: plugins/docker
  settings:
    repo: v7lin/frps
    context: frps
    dockerfile: Dockerfile
    target: prod
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
    - 0.22.0
    - latest

#trigger:
#  event:
#  - tag