# 版本
version: "3.7"

# 服务
services:

  test:
    container_name: test
    image: nginx:1.15.7
    restart: always
    hostname: test
#    ports:
#      - 80
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}

  frpc-test:
    container_name: frpc-test
    image: v7lin/frpc:0.23.3
    restart: always
    hostname: frpc-test
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "http"
      - "--proxy_name=test"
      - "--local_ip=test"
      - "--local_port=80"
      - "--sd=test" # subdomain
      - "--custom_domain=test.${SERVER_DOMAIN:-localhost}"
      - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
      - "--token=${FRP_TOKEN:-frp}"
#      - "--log_level=info"
    depends_on:
      - test
