# 版本
version: "3.7"

# 服务
services:

  www:
    container_name: www
    image: nginx:1.15.7
    restart: always
    hostname: www
#    ports:
#      - 80
    environment:
      - TZ=${TIME_ZONE}

  # 暂不支持设置时区
  frpc:
    container_name: frpc
    image: v7lin/frp:v0.22.0
    restart: always
    hostname: frpc
#    ports:
#      - 80 # vhost - http
#      - 443 # vhost - https
#      - 6000
#      - 7000 # bind
#      - 7500 # dashboard
    volumes:
      - ./frp/frpc.ini:/frpc.ini
#    environment:
#      - TZ=${TIME_ZONE}
    command: -c frpc.ini
    entrypoint:
      - /frpc
    depends_on:
      - www
