# --- clone ---

FROM arm64v8/alpine:3.8 as clone

ENV FRP_VERSION 0.24.1
ENV FRP_ARCH arm64

RUN wget https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz
RUN tar xzf frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz

# --- prod ---

FROM arm64v8/alpine:3.8 as prod

ENV FRP_VERSION 0.24.1
ENV FRP_ARCH arm64

RUN apk --no-cache add curl bash tree tzdata

# 让 Linux 像 Mac 一样支持 host.docker.internal
RUN apk --no-cache add iproute2

COPY --from=clone frp_${FRP_VERSION}_linux_${FRP_ARCH}/frpc /frpc

COPY docker-host.sh /docker-host.sh

WORKDIR /

ENTRYPOINT ['/docker-host.sh']
